/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package world.rightangle.rooms;

import java.awt.Color;

/**
 *
 * @author rightanglepro
 */
public class Room1 extends javax.swing.JFrame {

    /**
     * Creates new form Room1
     */
    public Room1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        room1Panel = new javax.swing.JPanel();
        lblRoomNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmboxColors = new javax.swing.JComboBox<>();
        btnPickColor = new javax.swing.JButton();
        btnReturnHallway = new javax.swing.JButton();
        btnQuitGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRoomNum.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblRoomNum.setText("Room 1");

        jLabel1.setText("Magical color changing wall???");

        cmboxColors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light Gray", "Gray", "White", "Red", "Yellow", "Green", "Blue" }));

        btnPickColor.setText("Pick");
        btnPickColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPickColorActionPerformed(evt);
            }
        });

        btnReturnHallway.setText("Return to Hallway");
        btnReturnHallway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnHallwayActionPerformed(evt);
            }
        });

        btnQuitGame.setText("Quit Game");
        btnQuitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout room1PanelLayout = new javax.swing.GroupLayout(room1Panel);
        room1Panel.setLayout(room1PanelLayout);
        room1PanelLayout.setHorizontalGroup(
            room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, room1PanelLayout.createSequentialGroup()
                        .addGap(0, 101, Short.MAX_VALUE)
                        .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(room1PanelLayout.createSequentialGroup()
                                .addComponent(cmboxColors, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPickColor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(353, 353, 353))
                    .addGroup(room1PanelLayout.createSequentialGroup()
                        .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoomNum)
                            .addGroup(room1PanelLayout.createSequentialGroup()
                                .addComponent(btnQuitGame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReturnHallway)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        room1PanelLayout.setVerticalGroup(
            room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(room1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRoomNum)
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboxColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPickColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addGroup(room1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitGame)
                    .addComponent(btnReturnHallway))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(room1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(room1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPickColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickColorActionPerformed
        String selectedColorItem = cmboxColors.getSelectedItem().toString();
        System.out.println("Room 1: Selected Color: " + selectedColorItem);
        
        Color selectedColor;
        
        if (selectedColorItem.equals("White")){
            selectedColor = new Color(242,242,242);
        }
        else if (selectedColorItem.equals("Gray")){
            selectedColor = new Color(192,192,192);
        }
        else if (selectedColorItem.equals("Red")){
            selectedColor = new Color(228,72,72);
        }
        else if (selectedColorItem.equals("Yellow")){
            selectedColor = new Color(255,225,38);
        }
        else if (selectedColorItem.equals("Green")){
            selectedColor = new Color(96,214,108);
        }
        else if (selectedColorItem.equals("Blue")){
            selectedColor = new Color(34,139,204);
        }
        else { // if selectedColorItem = "Light Gray" or something else
            selectedColor = new Color(214,217,223);
        }
        room1Panel.setBackground(selectedColor);
        System.out.println("DEBUG: " + getBackground().toString());
    }//GEN-LAST:event_btnPickColorActionPerformed

    private void btnReturnHallwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnHallwayActionPerformed
        // closes current window (returns to hallway window)
        System.out.println("Room 1: Return to Hallway");
        this.dispose();
    }//GEN-LAST:event_btnReturnHallwayActionPerformed

    private void btnQuitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitGameActionPerformed
        // quit game, exits program
        System.exit(0);
    }//GEN-LAST:event_btnQuitGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPickColor;
    private javax.swing.JButton btnQuitGame;
    private javax.swing.JButton btnReturnHallway;
    private javax.swing.JComboBox<String> cmboxColors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRoomNum;
    private javax.swing.JPanel room1Panel;
    // End of variables declaration//GEN-END:variables
}
